#spring.application.name=catch-table
server:
  port: 1017

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/catch_table
    username: root
    password: 1396

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

slack:
  channel:
    restaurant1: "한촌"
    restaurant2: "츠케루"
    restaurant3: "이태리"